apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: test-app
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: test-app
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: metrics
      interval: 15s